spring:
  profiles: default
  jpa:
#    show_sql: true
    format_sql: true
    hibernate:
      ddl-auto: create
    properties:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
          hbm2ddl:
            import_files: /initial_data_query.sql
  aop:
    proxy-target-class: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
#    url: jdbc:mariadb://localhost:3306/elk?useUnicode=true&characterEncoding=utf8
#    username: root
#    password: rhkfh1
#    driverClassName: org.mariadb.jdbc.Driver
#    validation-query: SELECT 1
#    test-on-borrow: true
    url: jdbc:mariadb://prepaymentdb.c0xvdbarxnyq.ap-northeast-2.rds.amazonaws.com:3306/elk_develop?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: core1502!
    driverClassName: org.mariadb.jdbc.Driver
    validation-query: SELECT 1
    test-on-borrow: true
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp